--
-- PostgreSQL database dump
--

\restrict 6xzGYuIUy43yjXU4aBkCDREQmpIag9yI3IOluAVUWqbtBQXqGiLjybA6FOgTRKk

-- Dumped from database version 17.11 (Debian 17.11-1.pgdg13+2)
-- Dumped by pg_dump version 17.11 (Debian 17.11-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: diagramas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.diagramas (
    id bigint NOT NULL,
    contenido jsonb NOT NULL,
    fecha_actualizacion timestamp(6) without time zone NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    version integer NOT NULL,
    proyecto_id bigint NOT NULL
);


--
-- Name: diagramas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.diagramas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diagramas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: miembros_tenant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.miembros_tenant (
    id bigint NOT NULL,
    fecha_union timestamp(6) without time zone NOT NULL,
    rol character varying(20) NOT NULL,
    tenant_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT miembros_tenant_rol_check CHECK (((rol)::text = ANY ((ARRAY['OWNER'::character varying, 'ADMIN'::character varying, 'MEMBER'::character varying])::text[])))
);


--
-- Name: miembros_tenant_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.miembros_tenant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.miembros_tenant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: miembros_workspace; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.miembros_workspace (
    id bigint NOT NULL,
    fecha_union timestamp(6) without time zone NOT NULL,
    rol character varying(20) NOT NULL,
    usuario_id bigint NOT NULL,
    workspace_id bigint NOT NULL,
    CONSTRAINT miembros_workspace_rol_check CHECK (((rol)::text = ANY ((ARRAY['OWNER'::character varying, 'EDITOR'::character varying, 'VIEWER'::character varying])::text[])))
);


--
-- Name: miembros_workspace_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.miembros_workspace ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.miembros_workspace_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proyectos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proyectos (
    id bigint NOT NULL,
    descripcion character varying(500),
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(100) NOT NULL,
    workspace_id bigint NOT NULL
);


--
-- Name: proyectos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proyectos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyectos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenants (
    id bigint NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(150) NOT NULL
);


--
-- Name: tenants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tenants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    email character varying(150) NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    rol_sistema character varying(20) NOT NULL,
    CONSTRAINT usuarios_rol_sistema_check CHECK (((rol_sistema)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspaces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspaces (
    id bigint NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(120) NOT NULL,
    tenant_id bigint NOT NULL
);


--
-- Name: workspaces_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workspaces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspaces_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diagramas diagramas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diagramas
    ADD CONSTRAINT diagramas_pkey PRIMARY KEY (id);


--
-- Name: miembros_tenant miembros_tenant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.miembros_tenant
    ADD CONSTRAINT miembros_tenant_pkey PRIMARY KEY (id);


--
-- Name: miembros_workspace miembros_workspace_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.miembros_workspace
    ADD CONSTRAINT miembros_workspace_pkey PRIMARY KEY (id);


--
-- Name: proyectos proyectos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos
    ADD CONSTRAINT proyectos_pkey PRIMARY KEY (id);


--
-- Name: tenants tenants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);


--
-- Name: diagramas uk_diagrama_proyecto; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diagramas
    ADD CONSTRAINT uk_diagrama_proyecto UNIQUE (proyecto_id);


--
-- Name: miembros_tenant uk_miembro_tenant_usuario_tenant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.miembros_tenant
    ADD CONSTRAINT uk_miembro_tenant_usuario_tenant UNIQUE (usuario_id, tenant_id);


--
-- Name: miembros_workspace uk_miembro_workspace_usuario_workspace; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.miembros_workspace
    ADD CONSTRAINT uk_miembro_workspace_usuario_workspace UNIQUE (usuario_id, workspace_id);


--
-- Name: usuarios ukkfsp0s1tflm1cwlj8idhqsad0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: workspaces workspaces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT workspaces_pkey PRIMARY KEY (id);


--
-- Name: workspaces fk6v30hhfbh8p2l8j0faybqvf7e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT fk6v30hhfbh8p2l8j0faybqvf7e FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: proyectos fk743ouw53ucpdut5k0yavlmymq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos
    ADD CONSTRAINT fk743ouw53ucpdut5k0yavlmymq FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id);


--
-- Name: miembros_tenant fkk4r0acekisjj4c5kxvlx4enwy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.miembros_tenant
    ADD CONSTRAINT fkk4r0acekisjj4c5kxvlx4enwy FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: diagramas fkmqb30kth09b94v0pj21bgieh0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diagramas
    ADD CONSTRAINT fkmqb30kth09b94v0pj21bgieh0 FOREIGN KEY (proyecto_id) REFERENCES public.proyectos(id);


--
-- Name: miembros_tenant fko013gdraq8dpecww49ge1kqsx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.miembros_tenant
    ADD CONSTRAINT fko013gdraq8dpecww49ge1kqsx FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: miembros_workspace fkqmbbpe7unr8h9sgrb8d4x40yf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.miembros_workspace
    ADD CONSTRAINT fkqmbbpe7unr8h9sgrb8d4x40yf FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id);


--
-- Name: miembros_workspace fktfl1l1c4rrvq4yrwlamqhx1q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.miembros_workspace
    ADD CONSTRAINT fktfl1l1c4rrvq4yrwlamqhx1q FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 6xzGYuIUy43yjXU4aBkCDREQmpIag9yI3IOluAVUWqbtBQXqGiLjybA6FOgTRKk

