package com.sw1.backend.ai.diagram.model;

public enum DiagramOperationType {
    ADD_ENTITY, DELETE_ENTITY, RENAME_ENTITY,
    ADD_ATTRIBUTE, DELETE_ATTRIBUTE, RENAME_ATTRIBUTE, CHANGE_ATTRIBUTE_TYPE,
    SET_ATTRIBUTE_PRIMARY_KEY, SET_ATTRIBUTE_NULLABLE,
    ADD_RELATIONSHIP, DELETE_RELATIONSHIP, UPDATE_RELATIONSHIP,
    CREATE_ASSOCIATION, DELETE_ASSOCIATION, CONVERT_MANY_TO_MANY_ASSOCIATION
}
