package com.sw1.backend.ai.agent.dto;

public enum AgentEventType {
    PROJECT_OPENED, DIAGRAM_OPENED, NODE_CREATED, NODE_SELECTED, NODE_UPDATED,
    NODE_DELETED, EDGE_CREATED, EDGE_UPDATED, EDGE_DELETED, DIAGRAM_SAVED,
    SAVE_FAILED, AI_REQUESTED
}
